module.exports = {
  apps: [
    {
      name: "game64x64",
      script: "src/server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: 3000,
        ENABLE_REDIS: "false",
        REDIS_URL: "redis://127.0.0.1:6379",
        REDIS_PLAYERS_KEY: "game64x64:players",
        REDIS_USERS_KEY: "game64x64:users",
        REDIS_SESSION_PREFIX: "game64x64:session:",
        REDIS_USER_SESSION_PREFIX: "game64x64:user-session:",
        MOVE_INTERVAL_MS: "16",
        SNAPSHOT_INTERVAL_MS: "250",
        AUTH_COOKIE_SECURE: "false",
        AUTH_SESSION_TTL_SEC: "86400",
        AUTH_REJECT_CONCURRENT: "true",
        AUTH_SEED_TEST_USERS: "true",
        AUTH_ALLOW_CONCURRENT_SEED_USERS: "true",
      },
      max_memory_restart: "300M",
      out_file: "./logs/out.log",
      error_file: "./logs/error.log",
      merge_logs: true,
      log_date_format: "YYYY-MM-DD HH:mm:ss",
      autorestart: true,
    },
  ],
};
